name: github pages

on:
  watch:
    types: [started]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Build Site
        uses: chabad360/hugo-gh-pages@master

      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          branch: master
          repo: goto10/goto10.github.io
          args: --gc --minify --cleanDestinationDir
